// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spbgxyvxhtgkxuzvhizf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwYmd4eXZ4aHRna3h1enZoaXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4Mzg2OTYsImV4cCI6MjA3NDQxNDY5Nn0.SdckRod0jHA6kJOU2zcEYZt9TXGtVXrawdkTX99g0xM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});